import { AbilityCategories } from '@/types/supabase.types';

export const abilitiesCategoryNames: Record<keyof AbilityCategories, string> = {
  damage: 'Damage',
  burst_damage: 'Burst Damage',
  weather: 'Weather',
  dot: 'DoT',
  damage_and_dot: 'Damage & DoT',
  team_damage: 'Team Damage',
  team_dot: 'Team DoT',
  self_damage: 'Self Damage',
  always_first: 'Always First',
  always_hits: 'Always Hits',
  always_kills: 'Always Kills',
  damage_from_backline: 'Damage From Backline',
  life_steal: 'Life Steal',
  healing: 'Healing',
  hot: 'HoT',
  team_healing: 'Team Healing',
  force_swaps: 'Force Swaps',
  interrupt: 'Interrupt',
  recoil: 'Recoil',
  remove_objects: 'Removes Objects',
  multiple_attacks: 'Multiple Attacks (2+)',
  best_when_first: 'Best When First',
  best_when_last: 'Best When Last',
  multiple_rounds: 'Multiple Rounds',
  persists_through_swaps: 'Persist Through Swaps',
  block: 'Block',
  dodge: 'Dodge',
  evasion: 'Evasion',
  silence: 'Silence',
  root: 'Root',
  thorn: 'Thorn',
  transformation: 'Transform',
  trap: 'Trap',
  minion_summoning: 'Minion/Object Summoning',
  purges_buffs_and_debuffs: 'Purges Buffs/Debuffs',
  becomes_unkillable: 'Becomes Unkillable',
  greater_chance_to_miss: 'Greater Miss Chance',
  cumulative_effects: 'Cumulative Effects',
  aquatic: 'Aquatic Abilities',
  beast: 'Beast Abilities',
  critter: 'Critter Abilities',
  dragonkin: 'Dragonkin Abilities',
  elemental: 'Elemental Abilities',
  flying: 'Flying Abilities',
  humanoid: 'Humanoid Abilities',
  magic: 'Magic Abilities',
  mechanical: 'Mechanical Abilities',
  undead: 'Undead Abilities',
  bonus_during_arcane_winds: 'Bonus During Arcane Winds',
  bonus_during_blizzard: 'Bonus During Blizzard',
  bonus_during_cleansing_rain: 'Bonus During Cleansing Rain',
  bonus_during_darkness: 'Bonus During Darkness',
  bonus_during_lightning_storm: 'Bonus During Lightning Storm',
  bonus_during_moonlight: 'Bonus During Moonlight',
  bonus_during_sunny_day: 'Bonus During Sunny Day',
  causes_bleeding: 'Causes Bleeding',
  causes_blinded: 'Causes Blinded',
  causes_burning: 'Causes Burning',
  causes_chilled: 'Causes Chilled',
  causes_poisoned: 'Causes Poisoned',
  causes_sleep: 'Causes Sleep',
  causes_stunned: 'Causes Stunned',
  causes_toxic_gas: 'Causes Toxic Gas',
  causes_webbed: 'Causes Webbed',
  bonus_to_bleeding: 'Bonus To Bleeding',
  bonus_to_blinded: 'Bonus To Blinded',
  bonus_to_burning: 'Bonus To Burning',
  bonus_to_chilled: 'Bonus To Chilled',
  bonus_to_low_health: 'Bonus To Low Health',
  bonus_to_poisoned: 'Bonus To Poisoned',
  bonus_to_stunned: 'Bonus To Stunned',
  bonus_to_toxic_gas: 'Bonus To Toxic Gas',
  bonus_to_webbed: 'Bonus To Webbed',
  accuracy_debuff: 'Accuracy Debuff',
  critical_strike_debuff: 'Crit Strike Debuff',
  damage_debuff: 'Damage Debuff',
  increased_damage_debuff: 'Increased Damage Debuff',
  reduced_healing_debuff: 'Reduced Healing Debuff',
  speed_debuff: 'Speed Debuff',
  team_debuff: 'Team Debuff',
  accuracy_buff: 'Accuracy Buff',
  critical_strike_buff: 'Crit Strike Buff',
  damage_buff: 'Damage Buff',
  damage_reduction_buff: 'Damage Reduction Buff',
  dodge_buff: 'Dodge Buff',
  healing_buff: 'Healing Buff',
  hit_point_buff: 'Hit Point Buff',
  speed_buff: 'Speed Buff',
  team_buff: 'Team Buff',
};
