export const allAbilities = {
  damage: [
    'Absorb',
    'Acid Rain',
    'Acid Touch',
    'Acidic Goo',
    'Ashes of Outland',
    'Adrenaline Rush',
    'Agony',
    "Akunda's Wrath",
    'Alert!',
    'Alluring Spores',
    'Alpha Strike',
    'Ambystan Snap',
    'Anvil Drop',
    'Apocalypse',
    'Arcane Barrage',
    'Arcane Blast',
    'Arcane Dash',
    'Arcane Explosion',
    'Arcane Riposte',
    'Arcane Shot',
    'Arcane Slash',
    'Arcane Storm',
    'Arm Cannon Blast',
    'Armageddon',
    'Avalanche',
    'Azerite Spike',
    'Backflip',
    'Banana Barrage',
    'Baneling Rush',
    'Baneling Burst',
    'Ban Hammer',
    'Barbed Stinger',
    'Bark',
    'Barrel Toss',
    'Batter',
    'Beam',
    'Belly Slide',
    'Bite',
    'Blast of Hatred',
    'Blazing Yip',
    'Blessed Hammer',
    'Blingtron Gift Package',
    'Blinkstrike',
    'Blistering Cold',
    'Blitz',
    'Blood Harvest',
    'Blood in the Water',
    'Bloodfang',
    'Body Slam',
    'Bombing Run',
    'BONESTORM',
    'BONESTORM!',
    'BONESTORM!!',
    'Bone Barrage',
    'Bone Bite',
    'Bone Prison',
    'Booby-Trapped Presents',
    'Bow Shot',
    'Breath',
    'Breath of Sorrow',
    'Brew Bolt',
    'Brittle Webbing',
    'Bronze Breath',
    'Broom',
    'Bubble Blast',
    'Build Turret',
    'Burn',
    'Burrow',
    'Burst',
    'Buuurp!',
    'Call Blizzard',
    'Call Darkness',
    'Call Lightning',
    'Call the Pack',
    'Call of Winter',
    'Cannon Shot',
    'Cataclysm',
    'Cataclysms Edge',
    'Carpnado',
    'Centrifugal Hooks',
    'Chain Lightning',
    'Chaos Beam',
    'Chaos Nova',
    'Charge',
    'Chew',
    'Chomp',
    'Chop',
    'Claw',
    'Clamp',
    'Clean-Up',
    'Cleave',
    'Club',
    'Cluck',
    'Cocoon Strike',
    'Coin Toss',
    'Comeback',
    'Competitive Spirit',
    'Conflagrate',
    'Confusing Sting',
    'Consume',
    'Contagion Strike',
    'Corpse Explosion',
    'Corrosion',
    'Corrupted Ground',
    'Corrupted Touch',
    'Cosmic Smash',
    'Counterspell',
    'Counterstrike',
    'Creeping Fungus',
    'Creeping Insanity',
    'Creeping Ooze',
    'Creepy Chomp',
    'Croak',
    'Crush',
    'Curse of Doom',
    'Cyclone',
    'Dark Bolt',
    'Dark Fate',
    'Dark Talon',
    'Darkflame',
    'Darkmoon Curse',
    'Dazzle',
    "Dead Man's Party",
    'Deadly Dreaming',
    'Death and Decay',
    'Death Coil',
    'Death Grip',
    'Deep Bite',
    'Deep Breath',
    'Deep Burn',
    'Deep Claw',
    'Deep Freeze',
    'Deep Snap',
    'Demolish',
    'Devastate',
    'Devour',
    'Devour the Weak',
    'Diseased Bite',
    'Discharge',
    'Dive',
    'Dive Bomb',
    "Dragon's Call",
    'Drain Blood',
    'Drain Power',
    'Dreadful Breath',
    'Drill Charge',
    'Dumpster Dive',
    'Early Advantage',
    'Egg Barrage',
    'Elementium Bolt',
    'Emerald Bite',
    'Empowering Strikes',
    'Entangling Roots',
    'Evolution',
    'Explode',
    'Explosive Brew',
    'Express Delivery',
    'Expunge',
    'Eye Beam',
    'Eyeblast',
    'Face Bite',
    'Face Punch',
    'Falcosaur Swarm!',
    'Falling Murloc',
    'Family Reunion',
    'Feast',
    'Feathered Frenzy',
    'Feed',
    'Feedback',
    'Fel Exhaust',
    'Fel Immolate',
    'Feral Clawstorm',
    'Feral Strike',
    'Fight and Flight',
    'Fire Quills',
    'Fire Shield',
    'First Croak',
    'Fish Slap',
    'Fist of the Forest',
    'Flame Breath',
    'Flame Jet',
    'Flame Shot',
    'Flamethrower',
    'Flank',
    'Flash',
    'Flash Freeze',
    'Flock',
    'Flurry',
    'Flux',
    'Flyby',
    'Focused Beams',
    'For The Alliance!',
    'For The Horde!',
    'Frenzy',
    'Frenzyheart Brew',
    'Frog Kiss',
    'Frost Breath',
    'Frost Nova',
    'Frost Shock',
    'Frost Shot',
    'Frost Spit',
    'Frostbite Webbing',
    'Frying Pan',
    'Furious Flapping',
    'Furious Surge',
    'Fury of 1,000 Fists',
    'Gale Slash',
    'Gargoyle Strike',
    'Gauss Rifle',
    'Geyser',
    'Ghostly Bite',
    'Gift of Winter Veil',
    'Gilded Fist',
    'Glop',
    'Glowing Toxin',
    'Gnash',
    'Gnaw',
    'Gobble Strike',
    'Gold Rush',
    'Goldskin',
    'Grasp',
    'Grave Destruction',
    'Gravity',
    'Great Cleave',
    'Great Sting',
    'Greed Before Need',
    "Greench's Gift",
    'Hammer',
    'Hate Mail',
    'Haunt',
    'Haymaker',
    'Haywire',
    'Headbutt',
    'Heat Up',
    'Heroic Leap',
    'Hiss',
    'Holy Blast',
    'Holy Charge',
    'Holy Nova',
    'Holy Strike',
    'Holy Sword',
    'Hoof',
    'Horn Attack',
    'Horn Gore',
    'Howling Blast',
    'Hubris',
    'Huge Fang',
    'Huge, Sharp Teeth!',
    'Hunting Party',
    'Ice Age',
    'Ice Lance',
    'Ice Spike',
    'Ice Tomb',
    'Icy Web',
    'Illuminate',
    'Immolate',
    'Immolation',
    'Impale',
    'Infected Claw',
    'Inferno Herding',
    'Inflation',
    'Instability',
    'Interrupting Gaze',
    'Interrupting Jolt',
    'Ironbark',
    'Ion Cannon',
    'Jab',
    'Jade Breath',
    'Jade Claw',
    'Jadefire Lightning',
    'Jar of Smelly Liquid',
    'Jolt',
    'Junk Mail',
    'Kick',
    "Krag'wa's Wrath",
    'Laser',
    'Lash',
    'Launch',
    'Launch Rocket',
    'Leap',
    'Leech Life',
    'Leech Seed',
    'Lens Flare',
    'Lick',
    'Life Exchange',
    'Life Sap',
    'Lift-Off',
    'Light',
    'Lightning Shield',
    'Lock-On',
    'Locust Swarm',
    'Logic',
    'Lumbering Charge',
    'Macabre Maraca',
    'Magic Hat',
    'Magic Sword',
    'Magma Trap',
    'Magma Wave',
    'Make it Rain',
    'Mana Flare',
    'Mana Surge',
    'Maul',
    'Meat Hook',
    'Mega Jolt',
    'Metabolic Boost',
    'Metal Fist',
    'Meteor Strike',
    'Mighty Charge',
    'Minefield',
    'Missile',
    'Money Meteor',
    'Moon Fang',
    'Moon Tears',
    'Moonfire',
    'Moth Balls',
    'Moth Dust',
    'Mud Rake',
    'Mudslide',
    'Mummy Wrap',
    'Murder',
    'Murder the Innocent',
    'Needle Claw',
    'Nether Blast',
    'Nether Gate',
    'Nibble',
    'Nightmare',
    "Niuzao's Charge",
    'Nocturnal Strike',
    'Nut Barrage',
    'Obsidian Bite',
    'Omni Pummel',
    'Omnislash',
    'Onyx Bite',
    'Ooze Touch',
    'Ott Breath',
    'Otter Breath',
    'Ottest Breath',
    'Overcharge',
    'Overtune',
    'Package Drop',
    'Paralyzing Shock',
    'Paralyzing Venom',
    'Peck',
    'Perfumed Arrow',
    'Personal Inferno',
    'Phase Punch',
    'Phaser',
    'Pheromones',
    'Pig Out',
    'Pinch',
    'Plague Breath',
    'Plagued Blood',
    'Plot Twist',
    'Poison Fang',
    'Poison Lash',
    'Poison Protocol',
    'Poison Spit',
    'Poisoned Branch',
    'Pounce',
    'Powerball',
    'Predatory Strike',
    'Primal Cry',
    'Proto-Strike',
    'Psionic Shockwave',
    'Psionic Storm',
    'Psychic Blast',
    'Pump',
    'Punch',
    'Puncture Wound',
    'Punish',
    'Puppies of the Flame',
    'Puppy Parade',
    'Quake',
    'Quick Attack',
    'Quicksand',
    'Quills',
    'Rabid Strike',
    'Railgun',
    'Raise Ally',
    'Rake',
    'Rampage',
    'Rapid Fire',
    'Ravage',
    'Ravenholdt Rush',
    'Rays of Light',
    'Reaping Hook',
    'Reckless Strike',
    'Reflective Shield',
    'Rend',
    'Rend Flesh',
    'Retrieve',
    'Return to Sender',
    'Rip',
    'Roar',
    'Rock Barrage',
    'Roll',
    'Rot',
    'Rupture',
    'Rush',
    'Sand bolt',
    'Sandstorm',
    'Savage Talon',
    'Scorched Earth',
    'Scrabble',
    'Scratch',
    'Screech',
    'Screeching Gears',
    'Seethe',
    'Sewage Eruption',
    'Shadow Bolt Volley',
    'Shadow Shock',
    'Shadow Slash',
    'Shadow Talon',
    'Shadowflame',
    'Shell Rush',
    'Shiverweb Swarm',
    'Shock and Awe',
    'Shot Through The Heart',
    'Shriek',
    'Siphon Anima',
    'Siphon Gear',
    'Siphon Life',
    'Skitter',
    'Skunky Brew',
    'Skull Toss',
    'Sleeping Gas',
    'Slicing Wind',
    'Slither',
    'Slime',
    'Slime Trail',
    'Slippery Ice',
    'Sloth Strike',
    'Slow and Steady',
    'Sludge Belch',
    'Sludge Claw',
    'Slow Unmaking',
    'Smash',
    'SMCKTHAT.EXE',
    'Snail Mail',
    'Snap',
    'Snap Trap',
    'Sneak Attack',
    'Sniff Out',
    'Snowball',
    'Solar Beam',
    'Sonic Blast',
    'Sons of the Flame',
    'Sons of the Root',
    'Soul Steal',
    'Soulrush',
    'Spark',
    'Spectral Spine',
    'Spectral Strike',
    'Spiderling Swarm',
    'Spiked Shell',
    'Spiked Skin',
    'Spill Hot Soup',
    'Spiny Carapace',
    'Spiritfire Bolt',
    'Spirit Claws',
    'Spirit Spikes',
    'Spiritfire Beam',
    'Spore Shrooms',
    'Squawk',
    'Squeeze',
    'Stampede',
    'Starfall',
    'Steady Snap',
    'Steam Vent',
    'Sticky Goo',
    'Sticky Grenade',
    'Sticky Web',
    'Sting',
    'Stoke the Flames',
    'Stone Rush',
    'Stone Shot',
    'Storm Breath',
    'Storm Coil',
    'Strike',
    'Stun Seed',
    'Sulfuras Smash',
    'Sunlight',
    'Super Sticky Goo',
    'Superbark',
    'Supercharge',
    'Surge',
    'Surge of Darkness',
    'Surge of Light',
    'Surge of Power',
    'Swallow You Whole',
    'Swarm',
    'Swarm of Bees',
    'Swarm of Flies',
    'Sweep',
    'Swipe',
    'Table of Discontents',
    'Tail Slap',
    'Tail Smash',
    'Tail Sweep',
    'Takedown',
    'Tea Party',
    'Tentacle Stab',
    'Tentacle Slap',
    'Terrifying Toxicity',
    'Tesla Cannon',
    'Thorns',
    'Thrash',
    'Thunderbolt',
    'Thunderclap',
    'Tidal Wave',
    'Time Bomb',
    'Tongue Lash',
    'Tornado Punch',
    'Touch of the Animus',
    'Toxic Bite',
    'Toxic Fumes',
    'Toxic Skin',
    'Toxic Smoke',
    'Toxic Spray',
    'Trample',
    'Transmute: Enemy to On Fire',
    'Trenchant Claws',
    'Trihorn Charge',
    'Triple Snap',
    'Trumpet Strike',
    'Twilight Fire',
    'Twilight Meteorite',
    'Tympanic Tantrum',
    'U-238 Rounds',
    'Udder Destruction',
    'Unleash Life',
    'Unrelenting Flames',
    'Unstable Shield',
    "Ursoc's Claws",
    'Vault Drop',
    'Vengeance',
    'Venomsleet Spit',
    'Vicious Fang',
    'Vicious Slice',
    'Vicious Streak',
    'Void Burst',
    'Void Crash',
    'Void Cyclone',
    'Void Nova',
    'Void Portal',
    'Void Slap',
    'Void Tremors',
    'Volcano',
    'Water Jet',
    'Weakening Blow',
    'Weakness',
    'When Elekks Fly',
    'Whirlpool',
    'Whirlwind',
    'Whirlwind Dance',
    'Whirling Talons',
    'Wild Winds',
    'Wind Buffet',
    'Wind Burst',
    'Wind-Up',
    'Windfury',
    'Wing Buffet',
    'Wombo Combo',
    'Woodchipper',
    'Worst Fear',
    'XE-321 Boombot',
    'Zap',
    'Zergling Rush',
    'Zoomies',
  ],
  burst_damage: [
    'Arcane Shot',
    'Azerite Spike',
    'Baneling Burst',
    'Barrel Toss',
    'Burst',
    'Cannon Shot',
    'Cataclysm',
    'Dark Bolt',
    'Deep Breath',
    'Deep Freeze',
    'Explode',
    'Expunge',
    'Fist of the Forest',
    'Flame Shot',
    'Frost Shot',
    'Haymaker',
    'Holy Charge',
    'Ice Spike',
    'Instability',
    'Ion Cannon',
    'Launch Rocket',
    'Lock-On',
    'Locust Swarm',
    'Lumbering Charge',
    'Mighty Charge',
    'Murder the Innocent',
    "Niuzao's Charge",
    'Pump',
    'Rend Flesh',
    'Shot Through The Heart',
    'Sloth Strike',
    'Slow and Steady',
    'Snail Mail',
    'Solar Beam',
    'Superbark',
    'Surge of Power',
    'Udder Destruction',
    'Void Burst',
    'When Elekks Fly',
    'Wind-Up',
    'Worst Fear',
  ],
  healing: [
    'Absorb',
    'Ancient Blessing',
    'Ancient Knowledge',
    'Aura of Gonk',
    'Bandage',
    'Bleat',
    'Blingtron Gift Package',
    'Buried Treasure',
    'Cauterize',
    'Cleansing Rain',
    'Consume',
    'Consume Corpse',
    'Consume Magic',
    'Death Coil',
    'Deliberate Retreat',
    'Devour',
    'Digest Brains',
    'Draconic Remedy',
    'Drain Blood',
    'Eat the Fly',
    'Emerald Dream',
    'Feed',
    "Giant's Blood",
    'Gift of the Naaru',
    'Healing Flame',
    'Healing Stream',
    'Healing Wave',
    'Healing Wrap',
    'Hibernate',
    'I Am Broot!',
    'Inspiring Song',
    'Leech Life',
    'Leech Seed',
    'Life Exchange',
    'Life Sap',
    'Light of Creation',
    'Love Potion',
    'Moon Tears',
    'Nap Time',
    "Nature's Touch",
    "Nature's Ward",
    'Nut-trition',
    'Perk Up',
    'Photosynthesis',
    'Pig Out',
    'Plagued Blood',
    'Plant',
    'Preen',
    'Rain Dance',
    'Ravage',
    'Rays of Light',
    'Reanimate',
    'Reboot',
    'Rebuild',
    'Reforge',
    'Renewing Mists',
    'Repair',
    'Restoration',
    'Rewind Time',
    'Siphon Anima',
    'Siphon Gear',
    'Siphon Life',
    'Soothing Mists',
    'Soul Steal',
    'Spa Day',
    'Stoke the Flames',
    'Touch of the Animus',
    'Tranquility',
    'Unleash Life',
    'Wish',
  ],
  dot: [
    'Acid Touch',
    'Acidic Goo',
    'Agony',
    'Alluring Spores',
    'Banana Barrage',
    'Barbed Stinger',
    'Blistering Cold',
    'Bone Barrage',
    'Build Turret',
    'Buuurp!',
    'Chop',
    'Confusing Sting',
    'Corpse Explosion',
    'Corrosion',
    'Corrupted Ground',
    'Corrupted Touch',
    'Creeping Fungus',
    'Creeping Ooze',
    'Deadly Dreaming',
    'Death and Decay',
    'Egg Barrage',
    'Fel Exhaust',
    'Fel Immolate',
    'Feral Clawstorm',
    'Flame Breath',
    'Flame Jet',
    'Flamethrower',
    'Gale Slash',
    'Glowing Toxin',
    'Gnash',
    'Great Sting',
    'Haunt',
    'Huge, Sharp Teeth!',
    'Immolate',
    'Immolation',
    'Junk Mail',
    'Leech Seed',
    'Make it Rain',
    'Mega Jolt',
    'Needle Claw',
    'Nut Barrage',
    'Ottest Breath',
    'Pheromones',
    'Poison Fang',
    'Poison Lash',
    'Poison Spit',
    'Poison Protocol',
    'Poisoned Branch',
    'Raise Ally',
    'Rip',
    'Rock Barrage',
    'Scorched Earth',
    'Siphon Life',
    'Sloth Strike',
    'Slow Unmaking',
    'Sludge Belch',
    'Spore Shrooms',
    'Sting',
    'Stoke the Flames',
    'Swarm of Bees',
    'Swarm of Flies',
    'Tentacle Stab',
    'Terrifying Toxicity',
    'Toxic Bite',
    'Toxic Smoke',
    'Twilight Fire',
    'Unrelenting Flames',
    'Venomsleet Spit',
    'Whirling Talons',
    'Wild Winds',
    'Woodchipper',
  ],
  hot: [
    'Emerald Dream',
    'Hibernate',
    'Nap Time',
    "Nature's Ward",
    'Photosynthesis',
    'Reanimate',
    'Renewing Mists',
    'Siphon Life',
    'Soothing Mists',
    'Spa Day',
    'Tranquility',
  ],
  damage_and_dot: [
    'Acid Touch',
    'Banana Barrage',
    'Barbed Stinger',
    'Bone Barrage',
    'Chop',
    'Corpse Explosion',
    'Corrupted Ground',
    'Corrupted Touch',
    'Creeping Ooze',
    'Egg Barrage',
    'Fel Exhaust',
    'Fel Immolate',
    'Flame Breath',
    'Flamethrower',
    'Gnash',
    'Huge, Sharp Teeth!',
    'Immolate',
    'Leech Seed',
    'Make it Rain',
    'Mega Jolt',
    'Needle Claw',
    'Nut Barrage',
    'Ottest Breath',
    'Poison Fang',
    'Poison Lash',
    'Poisoned Branch',
    'Rip',
    'Rock Barrage',
    'Scorched Earth',
    'Siphon Life',
    'Unrelenting Flames',
    'Wild Winds',
    'Woodchipper',
  ],
  team_damage: [
    'Acid Rain',
    "Akunda's Wrath",
    'Anvil Drop',
    'Arcane Explosion',
    'Arcane Storm',
    'Armageddon',
    'Avalanche',
    'Blood Harvest',
    'BONESTORM',
    'BONESTORM!',
    'BONESTORM!!',
    'Call of Winter',
    'Carpnado',
    'Chain Lightning',
    'Chaos Nova',
    'Cleave',
    'Cosmic Smash',
    'Cyclone',
    'Deliberate Retreat',
    'Dive Bomb',
    'Dreadful Breath',
    'Flux',
    'Fight and Flight',
    'Grave Destruction',
    'Great Cleave',
    'Great Sting',
    'Holy Nova',
    'Howling Blast',
    'Jadefire Lightning',
    "Krag'wa's Wrath",
    'Magma Wave',
    'Money Meteor',
    'Moon Tears',
    'Omnislash',
    'Pheromones',
    'Poison Protocol',
    'Primal Cry',
    'Psionic Shockwave',
    'Psionic Storm',
    'Quake',
    'Rapid Fire',
    'Rays of Light',
    'Shadow Bolt Volley',
    'Shell Rush',
    'Spiritfire Beam',
    'Starfall',
    'Storm Coil',
    'Sunlight',
    'Swipe',
    'Tea Party',
    'Thunderbolt',
    'Thunderclap',
    'Tidal Wave',
    'Twilight Meteorite',
    'Tympanic Tantrum',
    'Void Cyclone',
    'Void Nova',
    'Void Slap',
    'Whirling Talons',
    'Whirlwind',
  ],
  team_dot: [
    'Cyclone',
    'Great Sting',
    'Pheromones',
    'Poison Protocol',
    'Void Cyclone',
    'Whirling Talons',
  ],
  team_healing: [
    'Autumn Breeze',
    'Bleat',
    'Blood Harvest',
    'Cleansing Rain',
    'Draconic Remedy',
    'For Adventure!',
    'Haunting Song',
    'Healing Stream',
    'Inspiring Song',
    "Mother's Milk",
    'Ray of Hope',
    'Rays of Light',
    'Rebuild',
    'Starfall',
    'The Good Stuff',
  ],
  life_steal: [
    'Absorb',
    'Aura of Gonk',
    'Blingtron Gift Package',
    'Bloodfang',
    'Blood Harvest',
    'Consume',
    'Death Coil',
    'Devour',
    'Drain Blood',
    'Feed',
    'Leech Life',
    'Leech Seed',
    'Life Exchange',
    'Life Sap',
    'Moon Tears',
    'Pig Out',
    'Plagued Blood',
    'Ravage',
    'Rays of Light',
    'Siphon Anima',
    'Siphon Gear',
    'Siphon Life',
    'Starfall',
    'Stoke the Flames',
    'Soul Steal',
    'Touch of the Animus',
    'Unleash Life',
  ],
  damage_from_backline: ['Chew', 'Immolation'],
  force_swaps: [
    'Death Grip',
    'Deliberate Retreat',
    'Fade',
    'Feign Death',
    'Fight and Flight',
    'Hammer',
    'Inferno Herding',
    "krag'wa's Wrath",
    'Meat Hook',
    'Nether Gate',
    'Phase Punch',
    'Portal',
    'Reaping Hook',
    'Retrieve',
    'Return to Rest',
    'Return to Sender',
    'Righteous Inspiration',
    'Shell Rush',
    'Sweep',
    'Tail Smash',
    'Terrifying Toxicity',
    'Void Portal',
    'Warning!',
    'Warp',
    'Wind Buffet',
    'Wing Buffet',
  ],
  persists_through_swaps: [
    'Alluring Spores',
    'Ancient Knowledge',
    "Anzu's Blessing",
    'Bone Barrage',
    'Corrupted Ground',
    'Death and Decay',
    'Egg Barrage',
    'Elementium Bolt',
    'Entangling Roots',
    'Flamethrower',
    'Gale Slash',
    'Ice Tomb',
    'Immolation',
    'Make it Rain',
    'Mud Rake',
    'Mudslide',
    'Nut Barrage',
    'Pheromones',
    'Refuge',
    'Renewing Mists',
    'Rock Barrage',
    'Slippery Ice',
    'Soothing Mists',
    'Spore Shrooms',
    'Swarm of Bees',
    'Swarm of Flies',
    'Time Bomb',
    'Toxic Smoke',
    'Tranquility',
    'Void Crash',
    'Wild Winds',
  ],
  interrupt: [
    'Interrupting Jolt',
    'Interrupting Gaze',
    'Kick',
    'Backflip',
    'Paralyzing Venom',
    'Counterspell',
    'Nibble',
    'Horn Attack',
  ],
  block: [
    'Beaver Dam',
    'Bubble',
    'Cocoon Strike',
    'Decoy',
    'Deep Research',
    'Ice Barrier',
    'Illusionary Barrier',
    'Jade Barrier',
    'Mummy Trap',
    'Onyx Wall',
    'Prismatic Barrier',
    'Refuge',
    'Shell Fortress',
    'Shield Block',
    'Shieldstorm',
    'Soul Ward',
    'Weald Wall',
  ],
  dodge: [
    'Cute As A Button',
    'Dodge',
    'Dust Cloud',
    'Evanescence',
    'Frolick',
    'Phase Shift',
    'Queue Dodge',
    'Smoke Cloud',
    "Where's the Beef?",
  ],
  evasion: [
    'Ambystan Snap',
    'Anvil Drop',
    'Burrow',
    'Deflection',
    'Devastate',
    'Dive',
    'Dodge',
    'Dumpster Dive',
    'Dust Cloud',
    'Ethereal',
    'Evanescence',
    'Fade',
    'Feign Death',
    'Glop',
    'Heroic Leap',
    'Launch',
    'Lift-Off',
    'Meteor Strike',
    'Phase Shift',
    'Portal',
    'Proto-Strike',
    'Puppies of the Flame',
    'Queue Dodge',
    'Return to Rest',
    'Smoke Bomb',
    'Smoke Cloud',
    'Sons of the Flame',
    'Sons of the Root',
    'Vault Drop',
    'Void Portal',
    'Warning!',
    'Warp',
  ],
  silence: ['Nevermore'],
  root: [
    'Bone Prison',
    'Entangling Roots',
    'Frost Nova',
    'Grasp',
    'Gravity',
    'Icy Web',
    'Sewage Eruption',
    'Slime Trail',
    'Spa Day',
    'Sticky Goo',
    'Sticky Web',
    'Super Sticky Goo',
    'Void Tremors',
    'Whirlpool',
  ],
  thorn: [
    'Brittle Webbing',
    'Dark Fate',
    'Fire Shield',
    'Frostbite Webbing',
    'Heat Up',
    'Lighting Shield',
    'Mana Flare',
    'Reflective Shield',
    'Spiked Shell',
    'Spiked Skin',
    'Spiny Carapace',
    'Spirit Spikes',
    'Thorns',
    'Toxic Skin',
    'Unstable Shield',
  ],
  transformation: ["Nature's Ward", 'Rot'],
  trap: ['Magma Trap', 'Minefield', 'Snap Trap', 'Table of Discontents'],
  recoil: [
    'Mana Flare',
    'Unstable Shield',
    'Fire Shield',
    'Lightning Shield',
    'Heat Up',
    'Thorns',
    'Spiked Skin',
    'Spirit Spikes',
    'Toxic Skin',
    'Reflective Shield',
    'Brittle Webbing',
    'Spiny Carapace',
    'Frostbite Webbing',
  ],
  minion_summoning: [
    'Build Turret',
    'Puppies of the Flame',
    'Raise Ally',
    'Sons of the Flame',
    'Sons of the Root',
    'XE-321 Boombot',
  ],
  remove_objects: [
    'Tidal Wave',
    'Magma Wave',
    'Grave Destruction',
    'Clean-Up',
    'Sniff Out',
    'Sticky Surge',
  ],
  purges_buffs_and_debuffs: [
    'Aged Yolk',
    'Consume Magic',
    'Disruption',
    'Eggnog',
    'High Fiber',
    'Sear Magic',
  ],
  always_first: [
    'Void Portal',
    'Surge',
    'Belly Slide',
    'When Elekks Fly',
    'Drill Charge',
    'Trihorn Charge',
    'Quick Attack',
    'Blinkstrike',
    'Charge',
    'Express Delivery',
    'Bubble Blast',
    'Deflection',
    'Ethereal',
    'Love Potion',
    'Restoration',
    'Righteous Inspiration',
    'Shell Fortress',
    'Smoke Bomb',
  ],
  always_hits: ['Laser'],
  instant_kills: ['Apocalypse'],
  becomes_unkillable: ['Dark Rebirth', 'Survival'],
  self_damage: [
    'Void Portal',
    'Explode',
    'Burst',
    'Baneling Burst',
    'Stone Rush',
    'Gold Rush',
    'Body Slam',
    'Feral Strike',
    'BONESTORM',
    'BONESTORM!',
    'BONESTORM!!',
    'Armageddon',
  ],
  weather: [
    'Acid Rain',
    'Psionic Storm',
    'Arcane Storm',
    'Call Blizzard',
    'Call of Winter',
    'Call Darkness',
    'Call Lightning',
    'Illuminate',
    'Moonfire',
    'Mud Rake',
    'Mudslide',
    'Sandstorm',
    'Scorched Earth',
    'Moon Tears',
    'Starfall',
    'Sunlight',
    'Toxic Fumes',
    'Stoke the Flames',
  ],
  multiple_attacks: [
    'Devour the Weak',
    'Slicing Wind',
    'Triple Snap',
    'Flurry',
    'Thrash',
    'Batter',
    'Tongue Lash',
    'Lash',
    'Quills',
    'Blitz',
    'Fire Quills',
    'Rend',
    'Spark',
    'U-238 Rounds',
    'Steady Snap',
    'Arcane Barrage',
    'Flank',
    'Spiderling Swarm',
    'Make it Rain',
    'Bone Barrage',
    'Nut Barrage',
    'Egg Barrage',
    'Rock Barrage',
    'Banana Barrage',
    'Moth Balls',
    'Swarm',
    'Stampede',
    "Dead Man's Party",
    'Inflation',
    'Murder',
    'Junk Mail',
    'Zergling Rush',
    'Puppy Parade',
    'Family Reunion',
    'Flock',
    'Hunting Party',
    'Falcosaur Swarm!',
    'Omni Pummel',
    'Alert!',
    'Blessed Hammer',
    'Plot Twist',
    'Locust Swarm',
    'Call the Pack',
    'Wombo Combo',
    'Build Turret',
    'Furious Surge',
    'Shiverweb Swarm',
    'Zoomies',
    'Ravenholdt Rush',
  ],
  best_when_first: [
    'Arcane Slash',
    'Scrabble',
    'Pounce',
    'SMCKTHAT.EXE',
    'Alpha Strike',
    'Gnaw',
    'Flurry',
    'Thrash',
    'Batter',
    'Tongue Lash',
    'Lash',
    'Quills',
    'Blitz',
    'Fire Quills',
    'Rend',
    'Spark',
    'U-238 Rounds',
    'Arcane Barrage',
    'Flank',
    'Interrupting Jolt',
    'Interrupting Gaze',
    'Kick',
    'Backflip',
    'Paralyzing Venom',
    'Counterspell',
    'Nibble',
    'Horn Attack',
  ],
  best_when_last: [
    'Tail Sweep',
    'Counterstrike',
    'Blast of Hatred',
    'Steady Snap',
  ],
  multiple_rounds: [
    'Dreadful Breath',
    'Ravage',
    'Devour',
    'Solar Beam',
    'Sloth Strike',
    'Swarm',
    'Stampede',
    "Dead Man's Party",
    'Inflation',
    'Falling Murloc',
    'Hibernate',
    'Murder',
    'Lock-On',
    'Cannon Shot',
    'Junk Mail',
    'Barrel Toss',
    'Zergling Rush',
    'Puppy Parade',
    'Wombo Combo',
    'Spa Day',
    'Family Reunion',
    'Whirlwind Dance',
    'Emerald Dream',
    'Frost Shot',
    'Flock',
    'Hunting Party',
    'Falcosaur Swarm!',
    'Glop',
    'Burrow',
    'Dive',
    'Lift-Off',
    'Meteor Strike',
    'Proto-Strike',
    'Heroic Leap',
    'Launch',
    'Launch Rocket',
    'Dumpster Dive',
    'Devastate',
    'Flame Shot',
    'Vault Drop',
    'Deep Breath',
    'Deep Research',
    'Shot Through The Heart',
    'Holy Charge',
    "Niuzao's Charge",
    'Slow and Steady',
    'Lumbering Charge',
    'Snail Mail',
    'Haywire',
    'Rampage',
    'Eye Beam',
    'Tympanic Tantrum',
    'Quake',
    'Surge of Power',
    'Ion Cannon',
    'Locust Swarm',
    'Sons of the Flame',
    'Sons of the Root',
    'Puppies of the Flame',
    'Mana Surge',
    'Reanimate',
    'Reboot',
    'Reforge',
    'Ambystan Snap',
    'Anvil Drop',
    'Nap Time',
    'Repair',
    'Void Burst',
    "Akunda's Wrath",
    'Arcane Shot',
  ],
  greater_chance_to_miss: [
    'Banana Barrage',
    'Belly Slide',
    'Blingtron Gift Package',
    'Blood in the Water',
    'Bone Barrage',
    'Cataclysm',
    'Demolish',
    'Egg Barrage',
    'Feast',
    'Haymaker',
    'Ice Spike',
    'Instability',
    'Moth Balls',
    'Nocturnal Strike',
    'Nut Barrage',
    'Rock Barrage',
    'Spectral Strike',
    'Spirit Claws',
    'Trihorn Charge',
    'When Elekks Fly',
    'Worst Fear',
  ],
  cumulative_effects: [
    'Focused Beams',
    'Frog Kiss',
    'Gravity',
    'Nether Blast',
    'Powerball',
    'Vicious fang',
  ],
  aquatic: [
    'Acid Rain',
    'Acid Touch',
    'Ambystan Snap',
    'Blood in the Water',
    'Brew Bolt',
    'Bubble Blast',
    'Carpnado',
    'Cleansing Rain',
    'Creeping Ooze',
    'Croak',
    'Deep Bite',
    'Deep Claw',
    'Deep Snap',
    'Dive',
    'Eat the Fly',
    'First Croak',
    'Fish Slap',
    'Frog Kiss',
    'Frost Shot',
    'Gnash',
    'Grasp',
    'Healing Stream',
    'Healing Wave',
    'Healing Wrap',
    'Hot Soup',
    "Krag'wa's Wrath",
    'Needle Claw',
    'Otter Breath',
    'Pinch',
    'Pump',
    'Rain Dance',
    'Ray of Hope',
    'Renewing Mists',
    'Shell Fortress',
    'Shell Rush',
    'Spa Day',
    'Spiked Shell',
    'Spiny Carapace',
    'Squeeze',
    'Steady Snap',
    'Steam Vent',
    'Surge',
    'Swallow You Whole',
    'Tail Slap',
    'Tentacle Slap',
    'Tidal Wave',
    'Toxic Skin',
    'Toxic Spray',
    'Water Jet',
    'Whirlpool',
  ],
  beast: [
    'Aura of Gonk',
    'Banana Barrage',
    'Barbed Stinger',
    'Bark',
    'Barrel Toss',
    'Bash',
    'Bite',
    'Black Claw',
    'Blazing Yip',
    'Blinding Poison',
    'Bloodfang',
    'Brittle Webbing',
    'Burrow',
    'Call the Pack',
    'Claw',
    'Crystal Prison',
    'Cute Face',
    'Devour',
    'Devour the Weak',
    'Digest Brains',
    'Dominance',
    'Dust Cloud',
    'Enrage',
    'Exposed Wounds',
    'Face Bite',
    'Faceroll',
    'Feast',
    'Feed',
    'Feign Death',
    'Feral Strike',
    'Gnaw',
    'Going Bonkers!',
    'Great Sting',
    'Headbutt',
    'Hibernate',
    'Hiss',
    'Horn Attack',
    'Horn Gore',
    'Howl',
    'Huge Fang',
    'Huge, Sharp Teeth!',
    'Hunting Party',
    'Impale',
    'Knot of Snakes',
    'Leap',
    'Lick',
    'Lumbering Charge',
    'Mangle',
    'Maul',
    "Mother's Milk",
    'Mud Rake',
    'Nap Time',
    "Niuzao's Charge",
    'Paralyzing Venom',
    'Pheromones',
    'Pig Out',
    'Plot Twist',
    'Poison Fang',
    'Poison Protocol',
    'Poison Spit',
    'Pounce',
    'Primal Cry',
    'Prowl',
    'Puncture Wound',
    'Puppy Parade',
    'Rake',
    'Rampage',
    'Ravage',
    'Rend',
    'Rend Flesh',
    'Retrieve',
    'Rip',
    'Roar',
    'Rush',
    'Screech',
    'Shell Armor',
    'Shell Shield',
    'Skunky Brew',
    'Slither',
    'Sloth Strike',
    'Smash',
    'Snap',
    'Spiderling Swarm',
    'Spirit Claws',
    'Sticky Web',
    'Sting',
    'Strike',
    'Superbark',
    'Swipe',
    'Tail Smash',
    'Terrifying Toxicity',
    'The Good Stuff',
    'Trash',
    "Tough n' Cuddly",
    'Toxic Bite',
    'Trample',
    'Trihorn Charge',
    'Trihorn Shield',
    'Triple Snap',
    'Trumpet Strike',
    'Udder Destruction',
    "Ursoc's Claws",
    'Vengeance',
    'Vicious Fang',
    "Where's the Beef?",
    'Wombo Combo',
    'Woodchipper',
    'Zoomies',
  ],
  critter: [
    'Acidic Goo',
    'Adrenaline Rush',
    'Apocalypse',
    'Beaver Dam',
    'Bleat',
    'Buried Treasure',
    'Burst',
    'Chew',
    'Chomp',
    'Comeback',
    'Crouch',
    'Cute As A Button',
    'Dazzling Dance',
    'Deliberate Retreat',
    'Dumspter Dive',
    'Egg Barrage',
    'Family Reunion',
    'Feral Clawstorm',
    'Flank',
    'Flurry',
    'Food Coma',
    'Gobble Strike',
    'Hoof',
    'Locust Swarm',
    'Lucky Dance',
    'Lullaby',
    'Mudslide',
    "Nature's Touch",
    'Nibble',
    'Nut Barrage',
    'Nut-trition',
    'Perk Up',
    'Powerball',
    'Quick Attack',
    'Refuge',
    'Scrabble',
    'Scratch',
    'Skitter',
    'Slime Trail',
    'Slow and Steady',
    'Snail Mail',
    'Sneak Attack',
    'Sniff Out',
    'Soothe',
    'Stampede',
    'Stench',
    'Survival',
    'Swarm',
    'Swarm of Bees',
    'Swarm of Flies',
    'Tongue Lash',
    'Tranquility',
    'Trenchant Claws',
    'Uncanny Luck',
    'Vicious Streak',
  ],
  dragonkin: [
    'Ancient Blessing',
    'Ancient Knowledge',
    'Bend Time',
    'Breath',
    'Bronze Breath',
    'Cataclysm',
    'Deep Breath',
    'Devastate',
    'Draconic Remedy',
    "Dragon's Call",
    'Elementium Bolt',
    'Emerald Dream',
    'Emerald Presence',
    'Flame Breath',
    'Frost Breath',
    'Furious Surge',
    'Healing Flame',
    'Instability',
    'Jade Breath',
    'Life Sap',
    'Ott Breath',
    'Plague Breath',
    'Proto-Strike',
    'Roll',
    'Scorched Earth',
    'Shadowflame',
    'Shriek',
    'Sleeping Gas',
    'Sludge Claw',
    'Spiked Skin',
    'Starfall',
    'Tail Sweep',
    'Toxic Fumes',
    'Twilight Meteorite',
    'Unrelenting Flames',
  ],
  elemental: [
    "Akunda's Wrath",
    'Alluring Spores',
    'Ashes of Outland',
    'Autumn Breeze',
    'Avalanche',
    'Azerite Spike',
    'Barkskin',
    'Belly Slide',
    'Blistering Cold',
    'Breath of Sorrow',
    'Burn',
    'Buuurp!',
    'Call Blizzard',
    'Call of Winter',
    'Cauterize',
    'Chaos Nova',
    'Conflagrate',
    'Corrupted Ground',
    'Corrupted Touch',
    'Cosmic Smash',
    'Crystal Overload',
    'Dark Rebirth',
    'Darkflame',
    'Deep Burn',
    'Deep Freeze',
    'Discharge',
    'Early Advantage',
    'Entangling Roots',
    'Explosive Brew',
    'Fel Immolate',
    'Fire Quills',
    'Fire Shield',
    'Fist of the Forest',
    'Flame Jet',
    'Flame Shot',
    'Flamethrower',
    'Flash Freeze',
    'Frenzy',
    'Frost Nova',
    'Frost Shock',
    'Frost Spit',
    'Frostbite Webbing',
    'Geyser',
    'Gold Rush',
    'Goldskin',
    'Heat Up',
    'Holy Blast',
    'Holy Nova',
    'Howling Blast',
    'I Am Broot!',
    'Ice Age',
    'Ice Barrier',
    'Ice Lance',
    'Ice Spike',
    'Ice Tomb',
    'Icy Web',
    'Immolate',
    'Immolation',
    'Inebriate',
    'Inferno Herding',
    'Inspiring Song',
    'Ironbark',
    'Jolt',
    'Lash',
    'Leech Seed',
    'Lightning Shield',
    'Magma Trap',
    'Magma Wave',
    "Nature's Ward",
    'Obsidian Bite',
    'Ottest Breath',
    'Paralyzing Shock',
    'Photosynthesis',
    'Plant',
    'Poison Lash',
    'Poisoned Branch',
    'Puppies of the Flame',
    'Quicksand',
    'Railgun',
    'Reforge',
    'Rock Barrage',
    'Rupture',
    'Sand Bolt',
    'Seethe',
    'Shiverweb Swarm',
    'Slippery Ice',
    'Snowball',
    'Solar Beam',
    'Sons of the Flame',
    'Sons of the Root',
    'Soothing Mists',
    'Spark',
    'Spore Shrooms',
    'Sticky Goo',
    'Stone Rush',
    'Stone Shot',
    'Storm Breath',
    'Stun Seed',
    'Sulfuras Smash',
    'Sunlight',
    'Super Sticky Goo',
    'Thorns',
    'Thunderbolt',
    'Thunderclap',
    'Transmute: Enemy to On Fire',
    'Twilight Fire',
    'Unleash Life',
    'Unstable Shield',
    'Venomsleet Spit',
    'Volcano',
    'Weald Wall',
    'Windfury',
  ],
  flying: [
    'Accuracy',
    'Alpha Strike',
    "Anzu's Blessing",
    'Blood Harvest',
    'Caw',
    'Cluck',
    'Cocoon Strike',
    'Confusing Sting',
    'Cyclone',
    'Falcosaur Swarm!',
    'Feathered Frenzy',
    'Fight and Flight',
    'Flock',
    'Flyby',
    'Furious Flapping',
    'Glowing Toxin',
    'Hawk Eye',
    'Lift-Off',
    'Moth Balls',
    'Moth Dust',
    'Murder',
    'Nevermore',
    'Nocturnal Strike',
    'Peck',
    'Predatory Strike',
    'Preen',
    'Quills',
    'Reckless Strike',
    'Sandstorm',
    'Savage Talon',
    'Shadowmeld',
    'Slicing Wind',
    'Squawk',
    'Warning Squawk',
    'Whirling Talons',
    'Whirlwind Dance',
    'Wild Winds',
    'Wind Buffet',
    'Wind Burst',
  ],
  humanoid: [
    'Aged Yolk',
    'Amber Prison',
    'Backflip',
    'Ban Hammer',
    'Bandage',
    'Barrier Projector',
    'Blackout Kick',
    'Blinding Powder',
    'Blitz',
    'Body Slam',
    'Bow Shot',
    'Broom',
    'Bubble',
    'Call Darkness',
    'Cataclysms Edge',
    'Charge',
    'Clobber',
    'Club',
    'Contagion Strike',
    'Counterstrike',
    'Crush',
    'Dark Fate',
    'Dazzle',
    'Deflection',
    'Dodge',
    'Dreadful Breath',
    'Eggnog',
    'Express Delivery',
    'Eye Beam',
    'Face Punch',
    'Falling Murloc',
    'Focus',
    'Focus Chi',
    'For Adventure!',
    'For The Alliance!',
    'For The Horde!',
    'Frenzyheart Brew',
    'Frolick',
    'Fury of 1,000 Fists',
    'Gauss Rifle',
    "Giant's Blood",
    'Gift of the Naaru',
    'Gilded Fist',
    'Hate Mail',
    'Haymaker',
    'Heroic Leap',
    'High Fiber',
    'Holy Charge',
    'Holy Justice',
    'Holy Strike',
    'Holy Sword',
    "Itchin' for a Stitchin'",
    'Jab',
    'Jar of Smelly Liquid',
    'Junk Mail',
    'Kick',
    'Logic',
    'Love Potion',
    'Lovestruck',
    'Macabre Maraca',
    'Mass Resurrection',
    'Mighty Charge',
    'Murkmorphosis',
    'Nap Time',
    'Omnislash',
    'Overpowered',
    'Package Drop',
    'Perfumed Arrow',
    'Primal Rage',
    'Punch',
    'Punish',
    'Queue Dodge',
    'Rapid Fire',
    'Ravenholdt Rush',
    'Reflective Shield',
    'Restoration',
    'Shield Block',
    'Shieldstorm',
    'Shot Through The Heart',
    'Smoke Bomb',
    'Soul Ward',
    'Staggered Steps',
    'Surge of Darkness',
    'Surge of Light',
    'Takedown',
    'Tornado Punch',
    'Vicious Slice',
    'Weakening Blow',
    'Whirlwind',
    "Who's The Best Elekk In The Whole World?",
  ],
  magic: [
    'Adrenal Glands',
    'Amplify Magic',
    'Arcane Barrage',
    'Arcane Blast',
    'Arcane Dash',
    'Arcane Explosion',
    'Arcane Ripost',
    'Arcane Shot',
    'Arcane Slash',
    'Arcane Storm',
    'Baneling Burst',
    'Beam',
    'Blast of Hatred',
    'Blessed Hammer',
    'Blingtron Gift Package',
    'Blinkstrike',
    'Celestial Blessing',
    'Centrifugal Hooks',
    'Clean-Up',
    'Competitive Spirit',
    'Consume Magic',
    'Corrosion',
    'Counterspell',
    'Creeping Insanity',
    'dark Bolt',
    'Dark Talon',
    'Darkmoon Curse',
    'Deep Research',
    'Disruption',
    'Drain Power',
    "Elune's Grace",
    'Emerald Bite',
    'Ethereal',
    'Evanescence',
    'Evolution',
    'Expunge',
    'Eyeblast',
    'Fade',
    'Feedback',
    'Flash',
    'Focused Beams',
    'Forboding Curse',
    'Gift of Winter Veil',
    'Glop',
    'Gravity',
    'Greed Before Need',
    'Hatred Manifest',
    'Hubris',
    'Illuminate',
    'Illusionary Barrier',
    'Inner Vision',
    'Interrupting Gaze',
    'Invisibility',
    'Ironskin',
    'Jade Barrier',
    'Jade Claw',
    'Jadefire Lightning',
    'Jadeskin',
    'Laser',
    'Lens Flare',
    'Life Exchange',
    'Light',
    'Light of Creation',
    'Magic Hat',
    'Magic Sword',
    'Mana Flare',
    'Mana Surge',
    'Metabolic Boost',
    'Meteor Strike',
    'Moon Dance',
    'Moon Fang',
    'Moon Tears',
    'Moonfire',
    'Murder the Innocent',
    'Nether Blast',
    'Nether Gate',
    'Nightmare',
    'Nimbus',
    'Onyx Bite',
    'Onyx Wall',
    'Ooze Touch',
    'Phase Punch',
    'Phase Shift',
    'Phaser',
    'Plushie Rush',
    'Portal',
    'Prismatic Barrier',
    'Psionic Shockwave',
    'Psionic Storm',
    'Psychic Blast',
    'Rawr!',
    'Rays of Light',
    'Return to Sender',
    'Rewind Time',
    'Righteous Inspiration',
    'Sear Magic',
    'Sewage Eruption',
    'Shadow Bolt Volley',
    'Shadow Talon',
    'Slow Unmaking',
    'Soulrush',
    'Spectral Spine',
    'Spectral Strike',
    'Spirit Spikes',
    'Spiritfire Beam',
    'Spiritfire Bolt',
    'Stay a While and Listen',
    'Sticky Surge',
    'Stimpack',
    'Stoneskin',
    'Surge of Power',
    'Sweep',
    'Table of Discontents',
    'Temporal Anomaly',
    'Tentacle Stab',
    'Time Bomb',
    'Time Stop',
    'Uncertainty',
    'Void Burst',
    'Void Crash',
    'Void Cyclone',
    'Void Nova',
    'Void Portal',
    'Void Slap',
    'Void Tremors',
    'Weakness',
    'When Elekks Fly',
    'Wild Magic',
    'Wing Buffet',
    'Wish',
    'Worst Fear',
    'Zergling Rush',
  ],
  mechanical: [
    'Alert!',
    'Anvil Drop',
    'Arm Cannon Blast',
    'Armageddon',
    'Batter',
    'Bombing Run',
    'Booby-Trapped Presents',
    'Build Turret',
    'Call Lightning',
    'Cannon Shot',
    'Chain Lightning',
    'Chaos Beam',
    'Chop',
    'Clamp',
    'Coin Toss',
    'Decoy',
    'Demolish',
    'Dive Bomb',
    'Drill Charge',
    'Explode',
    'Extra Plating',
    'Fel Exhaust',
    'Flux',
    'Frying Pan',
    "Greench's Gift",
    'Hammer',
    'Haywire',
    'Heartbroken',
    'Inflation',
    'Interrupting Jolt',
    'Ion Cannon',
    'Launch',
    'Launch Rocket',
    'Lock-On',
    'Make it Rain',
    'Mega Jolt',
    'Metal Fist',
    'Minefield',
    'Missile',
    'Money Meteor',
    'Omni Pummel',
    'Overcharge',
    'Overtune',
    'Personal Inferno',
    'Quake',
    'Razor Talons',
    'Reaping Hook',
    'Reboot',
    'Rebuild',
    'Repair',
    'Screeching Gears',
    'Shock and Awe',
    'Siphon Anima',
    'Siphon Gear',
    'SMCKTHAT.EXE',
    'Smoke Cloud',
    'Snap Trap',
    'Sonic Blast',
    'Sticky Grenade',
    'Stoke the Flames',
    'Storm Coil',
    'Supercharge',
    'Tesla Cannon',
    'Touch of the Animus',
    'Toxic Smoke',
    'Tympanic Tantrum',
    'U-238 Rounds',
    'Unstable Engineering',
    'Vault Drop',
    'Warning!',
    'Warp',
    'Wind-Up',
    'XE-321 Boombot',
    'Zap',
  ],
  undead: [
    'Absorb',
    'Agony',
    'Bone Barrage',
    'Bone Bite',
    'Bone Prison',
    'BONESTORM',
    'BONESTORM!',
    'BONESTORM!!',
    'Cleave',
    'Consume',
    'Consume Corpse',
    'Corpse Explosion',
    'Creeping Fungus',
    'Creepy Chomp',
    'Curse of Doom',
    "Dead Man's Party",
    'Deadly Dreaming',
    'Death and Decay',
    'Death Coil',
    'Death Grip',
    'Diseased Bite',
    'Drain Blood',
    'Empowering Strikes',
    'Gale Slash',
    'Gargoyle Strike',
    'Ghostly Bite',
    'Grave Destruction',
    'Great Cleave',
    'Haunt',
    'Haunting Song',
    'Infected Claw',
    'Leech Life',
    'Meat Hook',
    'Mummy Wrap',
    'Plagued Blood',
    'Rabid Strike',
    'Raise Ally',
    'Raise Dead',
    'Reanimate',
    'Return to Rest',
    'Roar of the Dead',
    'Rot',
    'Shadow Shock',
    'Shadow Slash',
    'Siphon Life',
    'Skull Toss',
    'Slime',
    'Sludge Belch',
    'Soul Steal',
    'Stone Form',
    'Tea Party',
    'Unholy Ascension',
  ],
  bonus_during_arcane_winds: ['Mana Surge', 'Psionic Storm', 'Psychic Blast'],
  bonus_during_blizzard: ['Belly Slide'],
  bonus_during_cleansing_rain: ['Dreadful Breath'],
  bonus_during_darkness: ['Void Burst'],
  bonus_during_lightning_storm: ['Call Lightning', 'Storm Breath'],
  bonus_during_moonlight: [
    'Creeping Fungus',
    'Spirit Claws',
    'When Elekks Fly',
  ],
  bonus_during_sunny_day: ['Photosynthesis', 'Solar Beam', 'Surge of Darkness'],
  causes_bleeding: [
    'Chop',
    'Feral Clawstorm',
    'Huge, Sharp Teeth!',
    'Rip',
    'Woodchipper',
  ],
  causes_blinded: ['Blinding Poison', 'Call Darkness', 'Flash', 'Lens Flare'],
  causes_burning: [
    'Fel Immolate',
    'Flamethrower',
    'Immolate',
    'Scorched Earth',
    'Stoke the Flames',
  ],
  causes_chilled: [
    'Call Blizzard',
    'Flash Freeze',
    'Frost Nova',
    'Frost Shock',
    'Slippery Ice',
  ],
  causes_poisoned: [
    'Acidic Goo',
    'Blinding Poison',
    'Creeping Ooze',
    'Needle Claw',
    'Poison Fang',
    'Poison Lash',
    'Poison Spit',
    'Poisoned Branch',
    'Sludge Belch',
    'Terrifying Toxicity',
    'Toxic Fumes',
    'Venomsleet Spit',
  ],
  causes_sleep: [
    'Emerald Dream',
    'Food Coma',
    'Hibernate',
    'Lullaby',
    'Moth Dust',
    'Nap Time',
    'Sleeping Gas',
    'Soothe',
    'Stay a While and Listen',
  ],
  causes_stunned: [
    'Amber Prison',
    'Arcane Dash',
    'Bash',
    'Blackout Kick',
    'Clobber',
    'Crystal Prison',
    'Deep Freeze',
    'Elementium Bolt',
    'Faceroll',
    'Frog Kiss',
    'Frying Pan',
    'Fury of 1,000 Fists',
    'Geyser',
    'Headbutt',
    'Holy Justice',
    'Horn Attack',
    'Ice Age',
    'Ice Tomb',
    'Knot of Snakes',
    'Lovestruck',
    'Nibble',
    'Perfumed Arrow',
    'Rupture',
    'Screeching Gears',
    'Shock and Awe',
  ],
  causes_toxic_gas: ['Toxic Fumes'],
  causes_webbed: [
    'Brittle Webbing',
    'Frostbite Webbing',
    'Icy Web',
    'Sticky Web',
  ],
  bonus_to_bleeding: ['Blood in the Water', 'Feast', 'Maul'],
  bonus_to_blinded: [
    'Fury of 1,000 Fists',
    'Light',
    'Nocturnal Strike',
    'Sneak Attack',
    'Spectral Strike',
  ],
  bonus_to_burning: ['Conflagrate', 'Deep Burn', 'Personal Inferno'],
  bonus_to_chilled: ['Deep Freeze', 'Howling Blast', 'Ice Lance'],
  bonus_to_low_health: [
    'Aura of Gonk',
    'Comeback',
    'early Advantage',
    'Eat the Fly',
    'Impale',
    'Predatory Strike',
    'Swallow You Whole',
  ],
  bonus_to_poisoned: [
    'Contagion Strike',
    'Devour the Weak',
    'Puncture Wound',
    'Sludge Claw',
    'Vicious Fang',
  ],
  bonus_to_stunned: ['Takedown'],
  bonus_to_toxic_gas: ['Contagion Strike', 'Puncture Wound', 'Vicious Fang'],
  bonus_to_webbed: [
    'Devour the Weak',
    'Leech Life',
    'Shiverweb Swarm',
    'Spiderling Swarm',
  ],
  accuracy_debuff: [
    'Autumn Breeze',
    'Blinding Powder',
    'Dazzle',
    'Flash',
    'Inebriate',
    'Lens Flare',
    'Sandstorm',
    'Slippery Ice',
    'Stench',
    'Uncertainty',
    'Unstable Engineering',
  ],
  critical_strike_debuff: ['Croak'],
  damage_debuff: [
    'Bark',
    'Blazing Yip',
    'Cluck',
    'Darkmoon Curse',
    'Drain Power',
    'Jar of Smelly Liquid',
    'Rake',
    'Squawk',
    'Weakness',
  ],
  increased_damage_debuff: [
    'Acidic Goo',
    'Agony',
    "Akunda's Wrath",
    'Black Claw',
    'Call the Pack',
    'Corrosion',
    "Dead Man's Party",
    'Enrage',
    'Exposed Wounds',
    'Family Reunion',
    'Fight and Flight',
    'First Croak',
    'Flock',
    'Flyby',
    'Forboding Curse',
    'Greed Before Need',
    'Hatred Manifest',
    'Heartbroken',
    'Howl',
    'Hunting Party',
    'Inflation',
    'Junk Mail',
    'Mangle',
    'Murder',
    'Primal Rage',
    'Puppy Parade',
    'Rabid Strike',
    'Razor Talons',
    'Reckless Strike',
    'Roar of the Dead',
    'Stampede',
    'Swarm',
    'Toxic Spray',
    'Unholy Ascension',
    'Wild Magic',
    'Zergling Rush',
  ],
  reduced_healing_debuff: ['Breath of Sorrow', 'Call Darkness', 'Darkflame'],
  speed_debuff: [
    'Eyeblast',
    'Flash Freeze',
    'Forboding Curse',
    'Frost Shock',
    'Hiss',
    'Jar of Smelly Liquid',
    'Lick',
    'Moth Balls',
    'Primal Cry',
    'Prowl',
    'Quicksand',
    'Sand Bolt',
    'Screech',
    'Shadowmeld',
    'Sticky Surge',
    'Temporal Anomaly',
    'Weakness',
  ],
  team_debuff: [
    'Autumn Breeze',
    'Inebriate',
    'Stench',
    'Sticky Surge',
    'Temporal Anomaly',
    'Unholy Ascension',
    'Unstable Engineering',
  ],
  accuracy_buff: [
    'Accuracy',
    "Anzu's Blessing",
    'Focus',
    'Lucky Dance',
    'Nimbus',
    'Rain Dance',
    'Uncanny Luck',
  ],
  critical_strike_buff: [
    'Adrenal Glands',
    'Caw',
    'Going Bonkers!',
    'Hawk Eye',
    'Lucky Dance',
    'Murkmorphosis',
    'Overcharge',
    'Rain Dance',
    'Stimpack',
    'U-238 Rounds',
    'Uncanny Luck',
    'Uncertainty',
    'Unstable Engineering',
    'Warning Squawk',
  ],
  damage_buff: [
    'Amplify Magic',
    "Anzu's Blessing",
    'Competitive Spirit',
    'Crystal Overload',
    'Darkmoon Curse',
    'Dominance',
    'Drain Power',
    'Enrage',
    'Feathered Frenzy',
    'Focus Chi',
    'Frenzy',
    'Frenzyheart Brew',
    "Giant's Blood",
    'Greed Before Need',
    'Hate Mail',
    'Heartbroken',
    'I Am Broot!',
    'Inner vision',
    'Murkmorphosis',
    'Overpowered',
    'Preen',
    'Primal Rage',
    'Prowl',
    'Pump',
    'Rabid Strike',
    'Righteous Inspiration',
    'Roar',
    'Roll',
    'Shadowmeld',
    'Shriek',
    'Supercharge',
    'Trumpet Strike',
    'Wind-Up',
  ],
  damage_reduction_buff: [
    'Barkskin',
    'Barrier Projector',
    'Celestial Blessing',
    'Crouch',
    'Emerald Presence',
    'Extra Plating',
    'Goldskin',
    'Ironskin',
    'Jadeskin',
    'Sandstorm',
    'Shell Armor',
    'Shell Shield',
    'Shell Armor',
    'Spiked Shell',
    'Spiked Skin',
    'Spirit Spikes',
    'Staggered Steps',
    'Stoneskin',
    "Tough n' Cuddly",
    'Trihorn Shield',
  ],
  dodge_buff: ['Cute Face'],
  healing_buff: [
    'Illuminate',
    'Moonfire',
    'Ray of Hope',
    'Starfall',
    'Sunlight',
  ],
  hit_point_buff: [
    'Ancient Blessing',
    'Ancient Knowledge',
    'Illuminate',
    'Perk Up',
    'Sunlight',
  ],
  speed_buff: [
    'Adrenaline Rush',
    'Centrifugal Hooks',
    'Dazzling Dance',
    'Face Bite',
    'Furious Surge',
    'Gobble Strike',
    'Leap',
    'Metabolic Boost',
    'Moon Dance',
    'Overtune',
    'Powerball',
    'Righteous Inspiration',
    'Rush',
    'Vicious Streak',
    'Zoomies',
  ],
  team_buff: [
    'Accuracy',
    'Amplify Magic',
    'Ancient Blessing',
    'Dazzling Dance',
    'Decoy',
    'Lucky Dance',
    'Moon Dance',
    'Nimbus',
    'Perk Up',
    'Rain Dance',
    'Uncanny Luck',
    'Unstable Engineering',
  ],
};
